import { useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Anchor, ArrowRight, Check, CheckCircle2, ClipboardCheck, FileCheck2, Link2, PackagePlus, RotateCcw, Search, ShieldCheck, Ship, Sparkles, Truck, X, type LucideIcon } from 'lucide-react'
import confetti from 'canvas-confetti'
import { toast } from 'sonner'
import { avtomobiller, beyannameler, gemiler } from '../data/mockData'
import { Button, Card, PageHeader, StatusBadge } from '../components/UI'

export default function Registration() {
  const [shipId, setShipId] = useState('IMO9345678'); const [plate, setPlate] = useState('15 AA 859'); const [vehicleFound, setVehicleFound] = useState(false); const [declaration, setDeclaration] = useState(''); const [done, setDone] = useState(false)
  const ship = gemiler.find(g => g.id === shipId)!; const vehicle = avtomobiller.find(v => v.nomre === plate || v.kod === plate); const activeDeclarations = useMemo(() => beyannameler.filter(b => !vehicleFound || b.avtomobil === vehicle?.nomre || b.avtomobil === '15 AA 859').slice(0, 3), [vehicleFound, vehicle])
  const search = () => { if (vehicle) { setVehicleFound(true); toast.success('Avtomobil manifestdən avtomatik tapıldı') } else toast.error('Avtomobil tapılmadı — “15 AA 859” yazın') }
  const submit = () => { if (!vehicleFound || !declaration) return toast.warning('Bütün addımları tamamlayın'); setDone(true); confetti({ particleCount: 160, spread: 85, origin: { y: .65 }, colors: ['#0A4D8C', '#00B4D8', '#F4A261', '#2A9D8F'] }); toast.success('Vahid qeydiyyat uğurla tamamlandı') }
  const reset = () => { setVehicleFound(false); setDeclaration(''); setDone(false); setPlate('15 AA 859') }
  const registrationSteps: Array<[string, string, boolean, LucideIcon]> = [['1','Gəmi seçimi',!!ship,Ship],['2','Avtomobil axtarışı',vehicleFound,Truck],['3','Mal və bəyannamə',!!declaration,PackagePlus],['4','Təsdiq',done,ShieldCheck]]
  return <>
    <PageHeader eyebrow="ƏSAS DEMO · VAHİD ƏMƏLİYYAT" title="Vahid qeydiyyat" description="Gəmi, avtomobil və yük — üç ayrı prosesi bir ekranda tamamlayın" action={<div className="auto-mode"><span><i /> AVTOMATİK REJİM AKTİVDİR</span><small>AIS + Liman Vahid Pəncərəsi + Gömrük</small></div>} />
    <section className="value-ribbon"><div><Sparkles /><strong>3 səhifə əvəzinə 1 vahid axın</strong></div><span>Orta əməliyyat müddəti <del>18 dəq</del> <b>3 dəq</b></span><em>−83%</em></section>
    <nav className="registration-stepper" aria-label="Qeydiyyat addımları">{registrationSteps.map(([n,label,ok,Icon],i) => <div className={ok ? 'complete' : i === (vehicleFound ? declaration ? 3 : 2 : 1) ? 'active' : ''} key={n}><span>{ok ? <Check /> : <Icon />}</span><div><small>ADDIM {n}</small><strong>{label}</strong></div>{i < 3 && <i />}</div>)}</nav>
    <section className="registration-workspace">
      <Card className="registration-form" hover={false}>
        <section className="registration-step step-ship"><header><span className="step-number">01</span><div><h2>Gəmini seçin</h2><p>AIS tərəfindən limanda avtomatik qeydə alınmış gəmilər</p></div><CheckCircle2 className="step-check" /></header><label>Limandakı gəmi<select value={shipId} onChange={e => { setShipId(e.target.value); reset() }}>{gemiler.filter(g => g.status === 'Yanaşıb' || g.status === 'Manevrdə').map(g => <option value={g.id} key={g.id}>🚢 {g.ad} ({g.id}) — {g.status}</option>)}</select></label>
          <motion.div className="auto-data-panel" key={shipId} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}><span className="source-label"><RadioPulse /> AIS-DƏN AVTOMATİK</span><div className="data-grid"><Data label="Gəmi" value={ship.ad} /><Data label="IMO kodu" value={ship.id.replace('IMO','')} /><Data label="Kanal" value={ship.kanal} /><Data label="Giriş tarixi" value="25.06.2026 · 14:30" /><Data label="Mənşə" value={ship.menshe} /><Data label="Yük növü" value={ship.yuk} /></div></motion.div>
        </section>
        <section className="registration-step step-vehicle"><header><span className="step-number">02</span><div><h2>Avtomobili axtarın</h2><p>Nömrə və ya 13 rəqəmli qeydiyyat kodu ilə</p></div>{vehicleFound && <motion.span initial={{ scale: 0 }} animate={{ scale: 1 }}><CheckCircle2 className="step-check" /></motion.span>}</header><label>Avtomobil nömrəsi və ya kod<div className="search-field"><Search /><input value={plate} onChange={e => { setPlate(e.target.value.toUpperCase()); setVehicleFound(false) }} onKeyDown={e => e.key === 'Enter' && search()} placeholder="Məsələn: 15 AA 859"/><Button onClick={search}>Manifestdə axtar <ArrowRight /></Button></div></label>
          <AnimatePresence>{vehicleFound && vehicle && <motion.div className="auto-data-panel green" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}><span className="source-label"><Link2 size={14}/> LİMAN MANİFESTİNDƏN</span><div className="vehicle-head"><div className="truck-icon"><Truck /></div><div><strong>{vehicle.nomre}</strong><small>Bill of: {vehicle.kod}</small></div><StatusBadge status={vehicle.status} /></div><div className="data-grid"><Data label="Sürücü" value={vehicle.surucu} /><Data label="Nəqliyyat vasitəsi" value={vehicle.marka} /><Data label="Yük tipi" value={vehicle.yuk} /><Data label="Marşrut" value={`${vehicle.menshe} → ${vehicle.teyinat}`} /></div><p className="linked-note"><Anchor size={16}/> Avtomobil avtomatik olaraq <b>{ship.ad}</b> gəmisinin “Bill of” sənədinə bağlandı.</p></motion.div>}</AnimatePresence>
        </section>
        <section className={`registration-step step-goods ${!vehicleFound ? 'disabled-step' : ''}`}><header><span className="step-number">03</span><div><h2>Mal və bəyannamə əlavə edin</h2><p>Brokerin təqdim etdiyi aktiv GİB-lər avtomatik göstərilir</p></div>{declaration && <motion.span initial={{ scale: 0 }} animate={{ scale: 1 }}><CheckCircle2 className="step-check" /></motion.span>}</header>{vehicleFound ? <div className="declaration-picker"><span className="source-label"><FileCheck2 size={14}/> GÖMRÜK SİSTEMİNDƏN AVTOMATİK</span><p>{vehicle?.nomre} üçün <b>{activeDeclarations.length} aktiv bəyannamə</b> tapıldı. Seçmək üçün üzərinə klikləyin.</p>{activeDeclarations.map(b => <button className={declaration === b.kod ? 'selected' : ''} key={b.kod} onClick={() => { setDeclaration(b.kod); toast.success('Bəyannamə və mal məlumatları əlavə edildi') }}><span className="radio">{declaration === b.kod && <Check />}</span><div><strong>{b.kod}</strong><small>{b.broker} · {b.mallar[0].ad}</small></div><b>{b.umumiDeyer.toLocaleString('az-AZ')} {b.valyuta}</b><StatusBadge status={b.status} /></button>)}</div> : <div className="locked-note"><Truck /> Əvvəlcə avtomobil məlumatlarını tapın</div>}</section>
        <footer className="registration-actions"><Button variant="ghost" onClick={reset}><X/> Ləğv et</Button><div><small>{vehicleFound && declaration ? 'Bütün məlumatlar yoxlanılıb' : 'Davam etmək üçün addımları tamamlayın'}</small><Button variant="success" onClick={submit} className="confirm-btn" disabled={!vehicleFound || !declaration}><ClipboardCheck/> Yoxla və təsdiq et</Button></div></footer>
      </Card>
      <aside className="registration-summary"><Card hover={false}><header><ClipboardCheck/><div><h3>Əməliyyat xülasəsi</h3><p>Canlı olaraq yenilənir</p></div></header><div className="summary-chain"><SummaryItem ok title="Gəmi" value={`${ship.ad} · ${ship.id}`} /><SummaryItem ok={vehicleFound} title="Avtomobil" value={vehicleFound ? vehicle?.nomre || '' : 'Gözlənilir'} /><SummaryItem ok={!!declaration} title="Bəyannamə" value={declaration || 'Gözlənilir'} /><SummaryItem ok={done} title="Post qərarı" value={done ? '545 · Təsdiqləndi' : 'Təsdiqdən sonra yaranacaq'} /></div><div className="saving"><span>Vaxta qənaət</span><strong>~15 dəqiqə</strong><div><i style={{width: vehicleFound ? declaration ? '100%' : '66%' : '33%'}}/></div></div></Card><Card className="security-card" hover={false}><ShieldCheck/><div><strong>Məlumat təkrar daxil edilmir</strong><p>Hər sahənin mənbəyi və dəyişiklik tarixçəsi audit jurnalında saxlanılır.</p></div></Card></aside>
    </section>
    <AnimatePresence>{done && <motion.section className="success-overlay" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><motion.div initial={{ scale: .7 }} animate={{ scale: 1 }} transition={{ type: 'spring' }}><span><Check /></span><h2>Qeydiyyat tamamlandı!</h2><p>{ship.ad} · {vehicle?.nomre} · {declaration}</p><strong>Post qərar kodu: 545</strong><Button onClick={reset}>Yeni qeydiyyat başlat <RotateCcw /></Button></motion.div></motion.section>}</AnimatePresence>
  </>
}
function Data({ label, value }: {label:string; value:string}) { return <div><small>{label}</small><strong>{value}</strong></div> }
function SummaryItem({ ok, title, value }: {ok:boolean; title:string; value:string}) { return <div className={ok ? 'ok' : ''}><span>{ok ? <Check/> : <i/>}</span><div><small>{title}</small><strong>{value}</strong></div></div> }
function RadioPulse() { return <span className="tiny-pulse"><i/></span> }
