import { useMemo, useState } from 'react'
import { Filter, Plus, Search, Ship as ShipIcon, Waves } from 'lucide-react'
import { toast } from 'sonner'
import { gemiler } from '../data/mockData'
import SeaMap from '../components/SeaMap'
import { Button, Card, Modal, PageHeader, StatusBadge } from '../components/UI'

export default function Ships() {
  const [q, setQ] = useState(''); const [status, setStatus] = useState('Hamısı'); const [selected, setSelected] = useState<(typeof gemiler)[number] | null>(null)
  const rows = useMemo(() => gemiler.filter(g => (status === 'Hamısı' || g.status === status) && `${g.ad} ${g.id} ${g.yuk}`.toLocaleLowerCase('az').includes(q.toLocaleLowerCase('az'))), [q,status])
  return <><PageHeader eyebrow="AIS NƏZARƏT MƏRKƏZİ" title="Gəmi idarəetməsi" description="Xəzər dənizində gəmilərin avtomatik tanınması və liman əməliyyatları" action={<div className="header-actions"><span className="auto-badge"><i/> AVTOMATİK QEYDİYYAT AKTİVDİR</span><Button onClick={() => toast.info('Avtomatik rejim aktivdir — gəmi AIS vasitəsilə özü qeydə alınır')}><Plus/> Yeni gəmi</Button></div>} />
    <section className="ship-kpis"><Card><span><ShipIcon/></span><div><small>Aktiv gəmilər</small><strong>12</strong></div></Card><Card><span className="green"><Waves/></span><div><small>Yanaşan</small><strong>4</strong></div></Card><Card><span className="amber"><Waves/></span><div><small>Yaxınlaşan</small><strong>5</strong></div></Card><Card><span className="blue"><Waves/></span><div><small>Orta gözləmə</small><strong>1s 24d</strong></div></Card></section>
    <section className="ships-layout"><Card className="radar-panel" hover={false}><header className="card-heading"><div><span className="title-icon"><Waves/></span><div><h2>AIS radar paneli</h2><p>Avtomatik mövqe yenilənməsi · 10 san</p></div></div><span className="live-label"><i/> CANLI</span></header><SeaMap /></Card>
    <Card className="ship-table-card" hover={false}><header><div><h2>Gəmilər</h2><p>{rows.length} gəmi göstərilir</p></div><div className="table-tools"><label><Search/><input placeholder="Gəmi axtar..." value={q} onChange={e=>setQ(e.target.value)}/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option>Hamısı</option><option>Yanaşıb</option><option>Yaxınlaşır</option><option>Manevrdə</option><option>Yola çıxıb</option></select><button aria-label="Filtr"><Filter/></button></div></header><div className="table-scroll"><table><thead><tr><th>Gəmi / IMO</th><th>Yük</th><th>Status</th><th>Kanal</th><th>Sürət</th></tr></thead><tbody>{rows.map(g=><tr key={g.id} onClick={()=>setSelected(g)}><td><div className="ship-name"><span><ShipIcon/></span><div><strong>{g.ad}</strong><small>{g.id} · {g.bayraq}</small></div></div></td><td><strong>{g.yuk}</strong><small>{g.tonaj.toLocaleString('az-AZ')} ton</small></td><td><StatusBadge status={g.status}/></td><td>{g.kanal}</td><td>{g.suret} düyün</td></tr>)}</tbody></table></div></Card></section>
    <Modal open={!!selected} onClose={()=>setSelected(null)} title={selected?.ad||''}>{selected&&<div className="modal-detail"><div className="ship-visual"><div className="ship-3d"><span/></div></div><StatusBadge status={selected.status}/><dl><div><dt>IMO</dt><dd>{selected.id}</dd></div><div><dt>Mənşə</dt><dd>{selected.menshe}</dd></div><div><dt>Yük</dt><dd>{selected.yuk}</dd></div><div><dt>Tonaj</dt><dd>{selected.tonaj.toLocaleString()} ton</dd></div></dl><Button onClick={()=>toast.success('Gəmi əməliyyat səhifəsinə əlavə edildi')}>Əməliyyata başla</Button></div>}</Modal></>
}
